solved filteredObj
kinuesantos/algorithm pull request #31
Opened 2017-11-02 19:23 UTC by kinuesantos

2017-11-06 20:48 UTC, seemcat requested changes

2017-11-06 20:48 UTC, seemcat commented on solutions/filteredObj.js
> +  const func = (key,value,obj)=>{
why are you writing another function within a function? it doesn't seem like you're doing anything different. just take the extra inner function out

2017-11-06 20:48 UTC, seemcat commented on solutions/filteredObj.js
> +  const func = (key,value,obj)=>{
Also, where are you checking for the length of each value?? the point of filteredObj is to filter out the object but checking if each value (which is always a string)'s length is greater than 3.

2017-11-10 19:31 UTC, bramakrishna16 approved these changes

2017-11-10 19:59 UTC, merged